### ISSUE TITLE
Terraform Sate&Locking

### ISSUE THREAD

**Issue by yousefjnm** [yousefjnm/Project1#5]
Terraform tracks the state of changes made to your infrastructure over time. It is suggested that you do not use local state files but instead use a remote backend such as AWS Simple Storage Service (S3). S3 will allow your team to track state over time without worrying about one person overwriting the work of another.
You can also use AWS DynamoDB to "lock" changes from happening from multiple people at the same time. It is suggested that you use locking along with your remote state.
 Note that you should be able to use a single S3 bucket for all of your states but you may need to use separate tables for the DynamoDB locking.

See more at 
https://www.terraform.io/docs/backends/types/s3.html.

for more details, please check the instructions on Canvas

**Comment by JordanMayhem** [comment]
#create bucket
terraform {
    backend  "s3" {
    region         = "us-west-2"
    bucket         = "gitlegionbucket"
    key            = "ec2/terraform.tfstate" 
    dynamodb_table = "tf-state-lock"
    }
} 

provider “aws” {
  region = “us-west-2”
}

resource "aws_s3_bucket" "tf-remote-state" {
  bucket = "gitlegionbucket"

  versioning {
    enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_dynamodb_table" "dynamodb-tf-state-lock" {
  name            = "tf-state-lock"
  hash_key        = "LockID"
  read_capacity   = 20
  write_capacity = 20

  attribute {
    name = "LockID"
    type = "S"
  }

}
