### ISSUE TITLE
Ansible, Web server setup and configuration

### ISSUE THREAD

**Issue by yousefjnm** [yousefjnm/Project1#9]
You should only need to execute a single command to have both of the above tasks be 
completed. 

The first playbook will do everything to take a newly created instance and make it usable by the your application. You will need to install packages and configure the service to properly work for your application to work.

**Comment by jjd90** [comment]
I have created a playbook file in the Ansible directory which is not 100 percent complete. I will update this issue as i make progress.

**Comment by jjd90** [comment]
I was successful in running an Ansible playbook against a test EC2 instance remotely. The Playbook still requires some more code to install the web application that we will be utilizing.

**Comment by jjd90** [comment]
The ansible playbooks is done and it completely installs snipe-it on target servers.
